import { Feed } from "feed";
import type { ExtractedFeed } from "./schema";

/**
 * Build a `Feed` instance from our internal ExtractedFeed type.
 */
function buildFeed(
  feed: ExtractedFeed,
  selfUrl: string,
  format: "rss" | "atom"
): Feed {
  const description = feed.description
    ? `${feed.description} (Generated by RSS-O-Matic — rss-o-matic.com)`
    : "Generated by RSS-O-Matic — rss-o-matic.com";

  const feedLinks: Record<string, string> = {};
  if (format === "rss") {
    feedLinks.rss = selfUrl;
  } else {
    feedLinks.atom = selfUrl;
  }

  const f = new Feed({
    title: feed.title,
    description,
    id: feed.link,
    link: feed.link,
    generator: "RSS-O-Matic",
    updated: new Date(),
    feedLinks,
  });

  for (const item of feed.items) {
    const date = item.pubDate ? tryParseDate(item.pubDate) : null;

    f.addItem({
      title: item.title,
      id: item.link,
      link: item.link,
      description: item.description,
      date: date ?? new Date(),
      author: item.author ? [{ name: item.author }] : undefined,
      category: item.category ? [{ name: item.category }] : undefined,
      image: item.image,
    });
  }

  return f;
}

function tryParseDate(str: string): Date | null {
  const d = new Date(str);
  return isNaN(d.getTime()) ? null : d;
}

const RSS_XSL = '<?xml-stylesheet href="/pretty-feed-v3.xsl" type="text/xsl"?>';
const ATOM_XSL =
  '<?xml-stylesheet href="/pretty-atom.xsl" type="text/xsl"?>';

function injectStylesheet(xml: string, pi: string): string {
  return xml.replace(
    /(<\?xml [^?]+\?>)/,
    `$1\n${pi}`
  );
}

/**
 * Generate RSS 2.0 XML from an extracted feed.
 */
export function generateRssXml(feed: ExtractedFeed, selfUrl: string): string {
  const f = buildFeed(feed, selfUrl, "rss");
  return injectStylesheet(f.rss2(), RSS_XSL);
}

/**
 * Generate Atom 1.0 XML from an extracted feed.
 */
export function generateAtomXml(feed: ExtractedFeed, selfUrl: string): string {
  const f = buildFeed(feed, selfUrl, "atom");
  return injectStylesheet(f.atom1(), ATOM_XSL);
}
