import { generateAtomFeed, generateRssFeed } from "feedsmith";
import type { ExtractedFeed, FeedItem } from "./schema";

const RSS_STYLESHEET = { type: "text/xsl", href: "/pretty-feed-v3.xsl" };
const ATOM_STYLESHEET = { type: "text/xsl", href: "/pretty-atom.xsl" };

function feedDescription(feed: ExtractedFeed): string {
  return feed.description
    ? `${feed.description} (Generated by RSS-O-Matic — rss-o-matic.com)`
    : "Generated by RSS-O-Matic — rss-o-matic.com";
}

function itemDate(item: FeedItem): Date {
  if (item.pubDate) {
    const parsed = new Date(item.pubDate);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }

  return new Date();
}

function imageMimeType(url: string): string {
  let pathname: string;
  try {
    pathname = new URL(url).pathname.toLowerCase();
  } catch {
    return "image/*";
  }

  if (pathname.endsWith(".jpg")) return "image/jpg";
  if (pathname.endsWith(".jpeg")) return "image/jpeg";
  if (pathname.endsWith(".png")) return "image/png";
  if (pathname.endsWith(".gif")) return "image/gif";
  if (pathname.endsWith(".webp")) return "image/webp";
  if (pathname.endsWith(".svg")) return "image/svg+xml";
  return "image/*";
}

/** Generate RSS 2.0 XML from an extracted feed. */
export function generateRssXml(
  feed: ExtractedFeed,
  selfUrl: string,
  baseUrl?: string
): string {
  return generateRssFeed(
    {
      title: feed.title,
      link: feed.link,
      description: feedDescription(feed),
      generator: "RSS-O-Matic",
      lastBuildDate: new Date(),
      image: baseUrl
        ? {
            url: `${baseUrl}/favicon.svg`,
            title: feed.title,
            link: feed.link,
          }
        : undefined,
      atom: {
        links: [
          {
            href: selfUrl,
            rel: "self",
            type: "application/rss+xml",
          },
        ],
      },
      items: feed.items.map((item) => ({
        title: item.title,
        link: item.link,
        guid: { value: item.link, isPermaLink: false },
        pubDate: itemDate(item),
        description: item.description,
        content: item.content ? { encoded: item.content } : undefined,
        authors: item.author ? [{ name: item.author }] : undefined,
        categories: item.category ? [{ name: item.category }] : undefined,
        enclosures: item.image
          ? [{ url: item.image, length: 0, type: imageMimeType(item.image) }]
          : undefined,
      })),
    },
    { stylesheets: [RSS_STYLESHEET] }
  );
}

/** Generate Atom 1.0 XML from an extracted feed. */
export function generateAtomXml(
  feed: ExtractedFeed,
  selfUrl: string,
  baseUrl?: string
): string {
  return generateAtomFeed(
    {
      id: feed.link,
      title: { value: feed.title },
      subtitle: { value: feedDescription(feed) },
      updated: new Date(),
      generator: { text: "RSS-O-Matic" },
      icon: baseUrl ? `${baseUrl}/favicon.svg` : undefined,
      links: [
        { href: feed.link, rel: "alternate" },
        { href: selfUrl, rel: "self" },
      ],
      entries: feed.items.map((item) => ({
        id: item.link,
        title: { value: item.title, type: "html" },
        links: [
          { href: item.link },
          ...(item.image
            ? [
                {
                  href: item.image,
                  rel: "enclosure",
                  type: imageMimeType(item.image),
                },
              ]
            : []),
        ],
        updated: itemDate(item),
        summary: item.description
          ? { value: item.description, type: "html" }
          : undefined,
        content: item.content ? { value: item.content, type: "html" } : undefined,
        authors: item.author ? [{ name: item.author }] : undefined,
        categories: item.category
          ? [{ term: item.category, label: item.category }]
          : undefined,
      })),
    },
    { stylesheets: [ATOM_STYLESHEET] }
  );
}
