/**
 * Describes how to extract a value from an HTML element.
 * - If `attr` is set, extracts that attribute (e.g. "href", "src", "datetime").
 * - If `html` is true, extracts innerHTML instead of textContent.
 * - Otherwise, extracts textContent.
 */
export interface FieldSelector {
  /** CSS selector. For item fields, relative to the item element. Use "" to target the item itself. */
  selector: string;
  /** Attribute name to extract. If omitted, extracts textContent. */
  attr?: string;
  /** If true, extract innerHTML instead of textContent. Ignored if `attr` is set. */
  html?: boolean;
}

/**
 * Declarative parser configuration generated by AI.
 * Describes how to extract Atom feed data from a web page using CSS selectors.
 */
export interface ParserConfig {
  feed: {
    title: FieldSelector | string;
    description?: FieldSelector | string;
    link?: FieldSelector | string;
  };
  /** CSS selector matching each repeating item/article on the page */
  itemSelector: string;
  /** Field extractors, each relative to an item element */
  fields: {
    title: FieldSelector;
    link: FieldSelector;
    description?: FieldSelector;
    pubDate?: FieldSelector;
    author?: FieldSelector;
    category?: FieldSelector;
    image?: FieldSelector;
  };
}

export interface FeedItem {
  title: string;
  link: string;
  description?: string;
  content?: string;
  pubDate?: string;
  author?: string;
  category?: string;
  image?: string;
}

export interface ExtractedFeed {
  title: string;
  description: string;
  link: string;
  items: FeedItem[];
}

export interface DiscoveredFeed {
  url: string;
  title?: string;
  feedType: "rss" | "atom" | "json";
}

export interface SnapshotConfig {
  contentSelector: string;
  feedTitle: string;
}

export interface FeedRecord {
  id: string;
  url: string;
  title: string | null;
  type: "selector" | "snapshot";
  parser_config: string;
  created_at: string;
  updated_at: string;
}
